### ISSUE TITLE
OMHTTPRequest no response fail crash

### ISSUE THREAD

**Issue by agiokas** [b52/OMPromises#26]
- (void)connection:(NSURLConnection *)connection didFailWithError:(NSError *)error {

crashes if self.response is not initialised.

<img width="1293" alt="screen shot 2015-07-21 at 11 14 43 pm" src="https://cloud.githubusercontent.com/assets/1991666/8812758/617c11c4-2ffe-11e5-83f5-75edf851d1b6.png">

**Comment by b52** [comment]
Good catch, I'll write a fix and message you when it's done. I think it's also time to push a new version to CocoaPods.

**Comment by b52** [comment]
This one has already been fixed in 6d3f1b4613f8281cb1967b2632d90267a25f6913, which has not been released yet. I'll publish a new version just now.
