### ISSUE TITLE
waitForResultWithin OMPromiseStateFailed crashes if no error code is present

### ISSUE THREAD

**Issue by agiokas** [b52/OMPromises#27]
@throw [NSException exceptionWithName:@"WaitingForFufilledPromise"
                                           reason:@"The promise failed instead of getting fulfilled."
                                         userInfo:@{NSUnderlyingErrorKey: self.error}];

**Comment by b52** [comment]
Fixed in version 0.4.1, which I just pushed to CocoaPods.
